-- =====================================================================
-- Marketing Work Dashboard — shared store (SEPARATE Supabase project)
--
-- Run this ONCE on a NEW Supabase project (NOT the Adopt Me project).
-- Supabase is used here only to STORE submissions so the owner and the
-- worker see the same data. No login: the dashboard talks to this table
-- with the project's anon key (which lives in the HTML file).
--
-- Then paste your Project URL + anon public key into the CONFIG block at
-- the top of EMPLOYEE_DASHBOARD.html.
-- =====================================================================

create extension if not exists pgcrypto;

create table if not exists public.submissions (
  id          text primary key,         -- generated by the dashboard (uuid)
  operator    text,                     -- worker's name (typed in Settings)
  date        date,
  platform    text,
  activity    text,
  type        text,
  count       int  default 1,
  url         text,
  views       int  default 0,
  likes       int  default 0,
  notes       text,
  status      text default 'Pending',   -- Pending | Approved | Rejected
  ai_score    int,
  ai_verdict  text,                      -- good | bad
  ai_note     text,
  created_at  timestamptz default now()
);

alter table public.submissions enable row level security;

-- NO-LOGIN model: anyone with the anon key (it's in the HTML) may read/write.
-- Fine for a small private team with a non-public link. Switch to Supabase
-- Auth later if you want real per-person security.
grant select, insert, update, delete on public.submissions to anon;

drop policy if exists "anon full access" on public.submissions;
create policy "anon full access"
  on public.submissions for all
  to anon
  using (true)
  with check (true);

-- Live updates so the owner sees new worker entries without refreshing.
-- (Ignore the error if it says the table is already in the publication.)
alter publication supabase_realtime add table public.submissions;
