#!/usr/bin/env bash
#
# Scoped Cloud Functions deploy.
#
#   ./functions-deploy/deploy.sh mirrorUsersToSupabase cleanupOldPrivateChats
#   ./functions-deploy/deploy.sh --dry-run mirrorUsersToSupabase
#   ./functions-deploy/deploy.sh --list
#
# WHY THIS EXISTS
# ---------------
# ../functions has no index.js and ../firebase.json has no "functions" key, so
# `firebase deploy --only functions:...` from the repo root fails with
# "No targets in firebase.json match". Each function was historically deployed
# from its own folder with that single module renamed to index.js — you can see
# it in the deployed archives under
# gs://gcf-sources-541413670501-us-central1/<fn>-<uuid>/version-N/function-source.zip
#
# This script reproduces that safely: it stages the modules you name, generates
# an index.js exporting ONLY those functions, and always passes an explicit
# --only list. Two independent guards, so a mistake can't touch anything else.
#
# ⚠️  NEVER run a bare `firebase deploy --only functions` from here.
# The staged index.js is partial by design — a bare deploy would offer to
# DELETE every deployed function it doesn't see. Always name what you want.
#
# 2026-09-02: valueAlertsPoll (v2, scheduled) and notifyTradeAccept (v1,
# firestore document.create) were running in production with no source in this
# repo. Both have been recovered from the deployed archive and now live in
# ../functions, so the repo is the complete source of truth again.
#
# Also note ../functions still contains six modules that were deliberately
# DELETED from production in the 2026-07 pass — sendDeprecationCountdown (which
# was posting into RTDB chat every 3 minutes), sendUpdateNoticeMessage,
# notifyNewMessageLegacy, notifyGroupMessageLegacy, mirrorChatMetaToSupabase,
# mirrorPrivateMessageToSupabase. Naming one of those here would bring it back.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$HERE/../functions"
STAGING="$HERE/staging"
PROJECT="adoptme-7b50c"

# Functions that are live in production but have no source in ../functions.
# Listed so --list can warn rather than silently omitting them.
ORPHANS=""   # (was: valueAlertsPoll notifyTradeAccept — both recovered from GCS 2026-09-02)

# Modules whose functions were deleted from prod on purpose. Refuse to stage.
DANGER="sendDeprecationCountdown sendUpdateNoticeMessage notifyNewMessageLegacy notifyGroupMessageLegacy mirrorChatMetaToSupabase mirrorPrivateMessageToSupabase mirrorChatMetaToRtdb mirrorPrivateMessageToRtdb"

# Build "exportName<TAB>file.js" for every module in ../functions.
discover() {
  for f in "$SRC"/*.js; do
    base="$(basename "$f")"
    case "$base" in _*|*.local.js) continue ;; esac
    grep -o '^exports\.[A-Za-z0-9_]*' "$f" 2>/dev/null \
      | sed "s/^exports\.//" \
      | while read -r name; do [ -n "$name" ] && printf '%s\t%s\n' "$name" "$base"; done
  done
}

if [ "${1:-}" = "--list" ]; then
  echo "Deployable from ../functions:"
  discover | sort | awk -F'\t' '{printf "  %-32s %s\n", $1, $2}'
  if [ -n "$ORPHANS" ]; then
    echo
    echo "Live in production but NOT in this repo (recover before any full deploy):"
    for o in $ORPHANS; do echo "  $o"; done
  else
    echo
    echo "Every function deployed in production has source in ../functions."
  fi
  exit 0
fi

DRY_RUN=""
if [ "${1:-}" = "--dry-run" ]; then DRY_RUN="1"; shift; fi

if [ $# -eq 0 ]; then
  echo "usage: $0 [--dry-run] <functionName> [functionName...]" >&2
  echo "       $0 --list" >&2
  exit 1
fi

MAP="$(discover)"
rm -rf "$STAGING"; mkdir -p "$STAGING"

files=""
for fn in "$@"; do
  for d in $DANGER; do
    if [ "$fn" = "$d" ]; then
      echo "✖ refusing to deploy '$fn' — deleted from production on purpose (2026-07)." >&2
      exit 1
    fi
  done
  file="$(printf '%s\n' "$MAP" | awk -F'\t' -v n="$fn" '$1==n {print $2; exit}')"
  if [ -z "$file" ]; then
    echo "✖ no module in ../functions exports '$fn'." >&2
    for o in $ORPHANS; do
      [ "$fn" = "$o" ] && echo "  ('$fn' runs in production but its source is not in this repo — see the header.)" >&2
    done
    echo "  Run '$0 --list' to see what is available." >&2
    exit 1
  fi
  case " $files " in *" $file "*) ;; *) files="$files $file" ;; esac
done

# Stage only what is needed: the chosen modules, the shared Supabase helper,
# and the manifest. node_modules is symlinked, never copied or reinstalled —
# it is completely separate from the app's root node_modules and nothing here
# is bundled into the Android build.
for f in $files; do cp "$SRC/$f" "$STAGING/"; done
[ -f "$SRC/_supabaseAdmin.js" ] && cp "$SRC/_supabaseAdmin.js" "$STAGING/"
cp "$SRC/package.json" "$STAGING/"
[ -f "$SRC/package-lock.json" ] && cp "$SRC/package-lock.json" "$STAGING/"
ln -s "$SRC/node_modules" "$STAGING/node_modules"

{
  echo "// GENERATED by functions-deploy/deploy.sh — do not edit, do not commit."
  echo "// Exports exactly the functions named on the command line, nothing else."
  for fn in "$@"; do
    file="$(printf '%s\n' "$MAP" | awk -F'\t' -v n="$fn" '$1==n {print $2; exit}')"
    echo "exports.${fn} = require('./${file%.js}').${fn};"
  done
} > "$STAGING/index.js"

echo "▸ Staged $(echo $files | wc -w | tr -d ' ') module(s) for: $*"
node -e "const m=require('$STAGING/index.js');const got=Object.keys(m).sort().join(',');const want='$(printf '%s\n' "$@" | sort | tr '\n' ',' | sed 's/,$//')';if(got!==want){console.error('✖ export mismatch\n  got:  '+got+'\n  want: '+want);process.exit(1)}console.log('▸ index.js loads; exports exactly: '+got)"

ONLY="$(printf 'functions:%s,' "$@" | sed 's/,$//')"
if [ -n "$DRY_RUN" ]; then
  echo "▸ DRY RUN — would run:"
  echo "    firebase deploy --project $PROJECT --only $ONLY"
  exit 0
fi

echo "▸ Deploying --only $ONLY"
cd "$HERE"
firebase deploy --project "$PROJECT" --only "$ONLY"
